export const SET_PROFILE = "SET_PROFILE";
export const SET_SELECTION_ACCOUNT = "SET_SELECTION_ACCOUNT";
export const SET_SELECTION_ACCOUNT_CRYPTO = "SET_SELECTION_ACCOUNT_CRYPTO";
export const SET_SELECTION_CASHIER_TYPE = "SET_SELECTION_CASHIER_TYPE";
export const SET_SELECTION_TRADING_COIN_TYPE = "SET_SELECTION_TRADING_COIN_TYPE";
export const SET_MULTIPLIER = "SET_MULTIPLIER";
export const SET_SELECTION_STATISTICS_TAB = "SET_SELECTION_STATISTICS_TAB";


//Bitcoin Price Constants
export const SET_BITCOIN_PRICE = "SET_BITCOIN_PRICE";
export const SET_BITCOIN_PRICE_UPDOWN = "SET_BITCOIN_PRICE_UPDOWN";
export const SET_BITCOIN_24H_HIGH_PRICE = "SET_BITCOIN_24H_HIGH_PRICE";
export const SET_BITCOIN_24H_LOW_PRICE = "SET_BITCOIN_24H_LOW_PRICE";
export const SET_BITCOIN_24H_VOLUME = "SET_BITCOIN_24H_VOLUME";

//Ethereum Price Constants
export const SET_ETHEREUM_PRICE = "SET_ETHEREUM_PRICE";
export const SET_ETHEREUM_PRICE_UPDOWN = "SET_ETHEREUM_PRICE_UPDOWN";
export const SET_ETHEREUM_24H_HIGH_PRICE = "SET_ETHEREUM_24H_HIGH_PRICE";
export const SET_ETHEREUM_24H_LOW_PRICE = "SET_ETHEREUM_24H_LOW_PRICE";
export const SET_ETHEREUM_24H_VOLUME = "SET_ETHEREUM_24H_VOLUME";

//Solana Price Constants
export const SET_SOLANA_PRICE = "SET_SOLANA_PRICE";
export const SET_SOLANA_PRICE_UPDOWN = "SET_SOLANA_UPDOWN";
export const SET_SOLANA_24H_HIGH_PRICE = "SET_SOLANA_24H_HIGH_PRICE";
export const SET_SOLANA_24H_LOW_PRICE = "SET_SOLANA_24H_LOW_PRICE";
export const SET_SOLANA_24H_VOLUME = "SET_SOLANA_24H_VOLUME";

//APE Price Constants
export const SET_APE_PRICE = "SET_APE_PRICE";
export const SET_APE_PRICE_UPDOWN = "SET_APE_UPDOWN";
export const SET_APE_24H_HIGH_PRICE = "SET_APE_24H_HIGH_PRICE";
export const SET_APE_24H_LOW_PRICE = "SET_APE_24H_LOW_PRICE";
export const SET_APE_24H_VOLUME = "SET_APE_24H_VOLUME";

//ADA Price Constants
export const SET_ADA_PRICE = "SET_ADA_PRICE";
export const SET_ADA_PRICE_UPDOWN = "SET_ADA_UPDOWN";
export const SET_ADA_24H_HIGH_PRICE = "SET_ADA_24H_HIGH_PRICE";
export const SET_ADA_24H_LOW_PRICE = "SET_ADA_24H_LOW_PRICE";
export const SET_ADA_24H_VOLUME = "SET_ADA_24H_VOLUME";

//Bet record constant
export const SET_ADD_ACTIVE_BET_RECORD = "SET_ADD_ACTIVE_BET_RECORD";
export const SET_ACTIVE_BET_RECORD = "SET_ACTIVE_BET_RECORD";
export const SET_CLOSED_BET_RECORD = "SET_CLOSED_BET_RECORD";
export const SET_PUBLIC_BET_RECORD = "SET_PUBLIC_BET_RECORD";
export const SET_LEADERBOARD_RECORD = "SET_LEADERBOARD_RECORD";

//Authentication constants...
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const USER_BALANCE_REQUEST = "USER_BALANCE_REQUEST";
export const USER_BALANCE_SUCCESS = "USER_BALANCE_SUCCESS";
export const USER_BALANCE_FAIL = "USER_BALANCE_FAIL";
export const USER_BALANCE_RESET = "USER_BALANCE_RESET";

export const USER_WITHDRAW_REQUEST = "USER_WITHDRAW_REQUEST";
export const USER_WITHDRAW_SUCCESS = "USER_WITHDRAW_SUCCESS";
export const USER_WITHDRAW_FAIL = "USER_WITHDRAW_FAIL";
export const USER_WITHDRAW_RESET = "USER_WITHDRAW_RESET";
